on:
  push:
    branches: [stratosbot-landing-stack]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --fail --show-error --silent -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"
